name: Terraform Destroy RDS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Inicializar Terraform
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
